[package]
name = "ancdb-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
libc = "0.2"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[build-dependencies]
cc = "1.0"
