[package]
name = "ancdb-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
